name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: Dockerfile
        push: true
        tags: nitas12:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Kubernetes
      uses: actions/setup-kubectl@v1
      with:
        version: 'latest'

    - name: kubectl apply
      run: |
        kubectl apply -f ./nginx-deployment.yaml
        kubectl apply -f ./nginx-service.yaml
        kubectl apply -f ./mysql-statefulset.yaml
        kubectl apply -f ./mysql-service.yaml
        kubectl apply -f ./prometheus-deployment.yaml
        kubectl apply -f ./prometheus-config.yaml
        kubectl apply -f ./prometheus-service.yaml
        kubectl apply -f ./grafana-deployment.yaml
        kubectl apply -f ./grafana-service.yaml

