name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: nsasli/k8s-nginx:latest

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f nginx-deployment.yaml
        kubectl apply -f nginx-service.yaml
        kubectl apply -f mysql-statefulset.yaml
        kubectl apply -f mysql-service.yaml
